apiVersion: v1
kind: ConfigMap
metadata:
  name: consent-config
  labels:
    app: consent
data:
  PORT: "10001"
  DB_URL: "mongodb://mongo-service/pgd_data_consent"
  JWT_SECRET: "++F!NjHVZ67jaf5qn_bJhV73DJ&^^wkC"
  MINIO_ENDPOINT: "minio-service"
  MINIO_PORT: "9002"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  MINIO_BUCKET_NAME: "pgd-consents"
  REDIS_URL: "redis-service"
  REDIS_PORT: "6379"
  REDIS_PREFIX: "consent_"
  FRONT_END_URL: "http://dashboard-service:3000"
