apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    db: minio
spec:
  ports:
    - port: 9002

---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-service
  labels:
    db: minio
subsets:
  - addresses:
      - ip: 192.168.1.4
    ports:
      - port: 9002
