apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    db: mongo
spec:
  ports:
    - port: 27017

---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongo-service
  labels:
    db: mongo
subsets:
  - addresses:
      - ip: 192.168.1.4
    ports:
      - port: 27017
