apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    db: redis
spec:
  ports:
    - port: 6379

---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis-service
  labels:
    db: redis
subsets:
  - addresses:
      - ip: 192.168.1.4
    ports:
      - port: 6379
